=== CapeSepias/essentials/plugin-api/api/src/main/resources/instructions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.onehippo.org/essentials/instructions" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="instructions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="instructionSet">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="file" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="action" use="required"/>
                      <xs:attribute type="xs:string" name="source" use="optional"/>
                      <xs:attribute type="xs:string" name="target" use="optional"/>
                      <xs:attribute type="xs:string" name="overwrite" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="xml" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="action" use="required"/>
                      <xs:attribute type="xs:string" name="source" use="optional"/>
                      <xs:attribute type="xs:string" name="target" use="optional"/>
                      <xs:attribute type="xs:string" name="overwrite" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CapeSepias/essentials/dashboard-plugins/essentials-powerpacks/essentials-powerpack-basic/src/main/resources/META-INF/instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2013-2014 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->


<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
  <instructionSet>
    <cnd documentType="newsdocument" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated"/>
    <cnd documentType="eventsdocument" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated"/>
    <xml action="copy" source="xml/namespaces/newsdocument.xml" target="/hippo:namespaces/{{namespace}}"/>
    <xml action="copy" source="xml/namespaces/eventsdocument.xml" target="/hippo:namespaces/{{namespace}}"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/folderoptions/new-news-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-news-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-events-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-events-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
  </instructionSet>
  <instructionSet>
    <file action="copy" binary="true" overwrite="true" source="icons/new-folder-16.png" target="{{cmsRoot}}/src/main/resources/org/hippoecm/frontend/plugins/standardworkflow/new-news-folder-16.png"/>
    <file action="copy" binary="true" overwrite="true" source="icons/new-folder-16.png" target="{{cmsRoot}}/src/main/resources/org/hippoecm/frontend/plugins/standardworkflow/new-events-folder-16.png"/>
  </instructionSet>
  <instructionSet>
    <folder path="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}" template="xml/content/news.xml"/>
    <folder path="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}" template="xml/content/events.xml"/>
  </instructionSet>
  <instructionSet>
    <file action="copy" overwrite="true" source="jsp/essentials-layout-webpage.jsp" target="{{jspRoot}}/essentials/essentials-layout-webpage.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-standard-main.jsp" target="{{jspRoot}}/essentials/essentials-standard-main.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-list.jsp" target="{{jspRoot}}/essentials/essentials-component-list.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-menu.jsp" target="{{jspRoot}}/essentials/essentials-component-menu.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-document.jsp" target="{{jspRoot}}/essentials/essentials-component-document.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-news.jsp" target="{{jspRoot}}/essentials/essentials-component-news.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-news-detail.jsp" target="{{jspRoot}}/essentials/essentials-component-news-detail.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-events.jsp" target="{{jspRoot}}/essentials/essentials-component-events.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-event-detail.jsp" target="{{jspRoot}}/essentials/essentials-component-event-detail.jsp"/>
    <!--todo temporary:-->
    <file action="copy" overwrite="true" source="jsp/essentials-home.jsp" target="{{jspRoot}}/essentials/essentials-home.jsp"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/sitemap/news.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
    <xml action="copy" source="xml/hst/sitemap/events.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
    <!--todo temporary:-->
    <xml action="copy" source="xml/hst/sitemap/root.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
  </instructionSet>
  <instructionSet>
    <file action="copy" overwrite="true" source="java/NewsDocument.txt" target="{{beansFolder}}/NewsDocument.java"/>
    <file action="copy" overwrite="true" source="java/EventsDocument.txt" target="{{beansFolder}}/EventsDocument.java"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/components/list.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:components"/>
    <xml action="copy" source="xml/hst/components/content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:components"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/pages/standard.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/newsoverview.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/newspage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/eventsoverview.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/eventspage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <!--todo temporary:-->
    <xml action="copy" source="xml/hst/pages/homepage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/templates/layout-webpage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/standard-main.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/standard-menu.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/standard-main-overview-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/standard-main-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/news-main-overview-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/news-main-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/events-main-overview-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/events-main-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <!--todo temporary:-->
    <xml action="copy" source="xml/hst/templates/homepage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/catalog/basic-powerpack-catalog.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:catalog"/>
  </instructionSet>

  <!--
    MENU
  -->
  <instructionSet>
    <xml action="copy"  source="xml/hst/menu/main.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemenus"/>
  </instructionSet>
  <!--
    css
  -->
  <instructionSet>
    <xml action="copy" source="bootstrap/css/bootstrap.css" target="{{siteWebRoot}}/css/bootstrap.css"/>
    <xml action="copy" source="bootstrap/css/bootstrap.min.css" target="{{siteWebRoot}}/css/bootstrap.min.css"/>
    <xml action="copy" source="bootstrap/fonts/glyphicons-halflings-regular.eot" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.eot"/>
    <xml action="copy" source="bootstrap/fonts/glyphicons-halflings-regular.svg" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.svg"/>
    <xml action="copy" source="bootstrap/fonts/glyphicons-halflings-regular.ttf" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.ttf"/>
    <xml action="copy" source="bootstrap/fonts/glyphicons-halflings-regular.woff" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.woff"/>
  </instructionSet>


  <!-- SAMPLES GROUP-->
  <instructionSet group="samples">
    <xml action="copy" source="xml/samples/content/documents/events/sample_breakfast.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/events/sample_introduction_speech.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/events/sample_workshop.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_medusa.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_harvest.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_gastropoda.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/gallery/samples.xml" target="/content/gallery/{{namespace}}"/>
  </instructionSet>
</instructions>

=== CapeSepias/essentials/dashboard-plugins/essentials-powerpacks/essentials-powerpack-basic/src/test/resources/META-INF/instructions.xml
<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
  <instructionSet name="JSP">
    <file action="copy" overwrite="true" source="jsp/essentials-component-document.jsp" target="${tmpFolder}/essentials/essentials-component-document.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-events.jsp" target="${tmpFolder}/essentials/essentials-component-events.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-event-detail.jsp" target="${tmpFolder}/essentials/essentials-component-event-detail.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-list.jsp" target="${tmpFolder}/essentials/essentials-component-list.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-news.jsp" target="${tmpFolder}/essentials/essentials-component-news.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-component-news-detail.jsp" target="${tmpFolder}/essentials/essentials-component-news-details.jsp"/>
  </instructionSet>
  <instructionSet name="SITE-MAPS">
    <xml action="copy" source="xml/sitemap-news.xml" target="/hst:hst/hst:configurations/${namespace}/hst:sitemap"/>
  </instructionSet>
  <instructionSet name="COMPONENTS">
    <xml action="copy" source="xml/component-news.xml" target="/hst:hst/hst:configurations/${namespace}/hst:components"/>
  </instructionSet>
  <instructionSet name="JAVA">
    <file action="copy" overwrite="true" source="java/NewsDocumentBean.java" target="${tmpFolder}/${beansFolder}/NewsDocumentBean.java"/>
  </instructionSet>
  <instructionSet name="PAGES">
    <xml action="copy" source="xml/page-news.xml" target="/hst:hst/hst:configurations/${namespace}/hst:pages"/>
    <xml action="copy" source="xml/page-newsoverview.xml" target="/hst:hst/hst:configurations/${namespace}/hst:pages"/>
  </instructionSet>
  <instructionSet name="TEMPLATES">
    <xml action="copy" source="xml/template-news-overview.xml" target="/hst:hst/hst:configurations/${namespace}/hst:templates"/>
  </instructionSet>

</instructions>

=== CapeSepias/essentials/dashboard-plugins/essentials-powerpacks/essentials-powerpack-basic/src/main/resources/META-INF/basic_powerpack_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2013-2014 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->


<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
  <instructionSet>
    <cnd documentType="newsdocument" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated"/>
    <cnd documentType="eventsdocument" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated"/>
    <xml action="copy" source="xml/namespaces/newsdocument.xml" target="/hippo:namespaces/{{namespace}}"/>
    <xml action="copy" source="xml/namespaces/eventsdocument.xml" target="/hippo:namespaces/{{namespace}}"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/folderoptions/new-news-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-news-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-events-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-events-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
  </instructionSet>
  <instructionSet>
    <file action="copy" binary="true"  source="icons/new-folder-16.png" target="{{cmsRoot}}/src/main/resources/org/hippoecm/frontend/plugins/standardworkflow/new-news-folder-16.png"/>
    <file action="copy" binary="true"  source="icons/new-folder-16.png" target="{{cmsRoot}}/src/main/resources/org/hippoecm/frontend/plugins/standardworkflow/new-events-folder-16.png"/>
  </instructionSet>
  <instructionSet>
    <folder path="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}" template="xml/content/news.xml"/>
    <folder path="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}" template="xml/content/events.xml"/>
  </instructionSet>
  <instructionSet>


    <file action="copy" source="jsp/essentials-component-list.jsp" target="{{jspRoot}}/essentials/essentials-component-list.jsp"/>
    <file action="copy"  source="jsp/essentials-component-document.jsp" target="{{jspRoot}}/essentials/essentials-component-document.jsp"/>
    <file action="copy"  source="jsp/essentials-component-news.jsp" target="{{jspRoot}}/essentials/essentials-component-news.jsp"/>
    <file action="copy"  source="jsp/essentials-component-news-detail.jsp" target="{{jspRoot}}/essentials/essentials-component-news-detail.jsp"/>
    <file action="copy"  source="jsp/essentials-component-events.jsp" target="{{jspRoot}}/essentials/essentials-component-events.jsp"/>
    <file action="copy"  source="jsp/essentials-component-event-detail.jsp" target="{{jspRoot}}/essentials/essentials-component-event-detail.jsp"/>

  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/sitemap/news.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
    <xml action="copy" source="xml/hst/sitemap/events.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
  </instructionSet>
  <instructionSet>
    <file action="copy"  source="java/NewsDocument.txt" target="{{beansFolder}}/NewsDocument.java"/>
    <file action="copy"  source="java/EventsDocument.txt" target="{{beansFolder}}/EventsDocument.java"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/components/list.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:components"/>
    <xml action="copy" source="xml/hst/components/content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:components"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/pages/standard.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/newsoverview.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/newspage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/eventsoverview.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/eventspage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>

  </instructionSet>
  <instructionSet>

    <xml action="copy" source="xml/hst/templates/standard-main-overview-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/standard-main-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/news-main-overview-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/news-main-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/events-main-overview-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/events-main-content.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="xml/hst/catalog/basic-powerpack-catalog.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:catalog"/>
  </instructionSet>

  <!--
    MENU
  -->
  <instructionSet>
    <xml action="copy" source="xml/menu/menu-item-news.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemenus/main"/>
    <xml action="copy" source="xml/menu/menu-item-events.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemenus/main"/>
  </instructionSet>



  <!-- SAMPLES GROUP-->
  <instructionSet group="samples">
    <xml action="copy" source="xml/samples/content/documents/events/sample_breakfast.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/events/sample_introduction_speech.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/events/sample_workshop.xml" target="/content/documents/{{namespace}}/events/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_medusa.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_harvest.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_gastropoda.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/gallery/samples.xml" target="/content/gallery/{{namespace}}"/>
  </instructionSet>
</instructions>

=== CapeSepias/essentials/plugins/news/src/main/resources/META-INF/news_package_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2014 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->


<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">


  <instructionSet>
    <cnd documentType="newsdocument" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated"/>
    <xml action="copy" source="xml/namespaces/newsdocument.xml" target="/hippo:namespaces/{{namespace}}"/>
  </instructionSet>


  <instructionSet group="jsp">
    <file action="copy" source="jsp/newslist-main-newslist.jsp" target="{{jspRoot}}/hstdefault/newslist-main-newslist.jsp"/>
    <file action="copy" source="jsp/newspage-main.jsp" target="{{jspRoot}}/{{namespace}}/newspage-main.jsp"/>
    <xml action="copy" source="xml/hst/templates/news-main-content-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/newslist-main-newslist-jsp.xml" target="/hst:hst/hst:configurations/hst:default/hst:templates"/>

  </instructionSet>

  <instructionSet group="freemarker, repository">

    <freemarker action="copy" source="freemarker/newslist-main-newslist.ftl" target="{{freemarkerRoot}}/hstdefault/newslist-main-newslist.ftl"/>
    <freemarker action="copy" source="freemarker/newspage-main.ftl" target="{{freemarkerRoot}}/{{namespace}}/newspage-main.ftl"/>
  </instructionSet>
  <instructionSet group="freemarker">
    <xml action="copy" source="xml/hst/templates/news-main-content-freemarker.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="xml/hst/templates/newslist-main-newslist-freemarker.xml" target="/hst:hst/hst:configurations/hst:default/hst:templates"/>
  </instructionSet>

  <instructionSet>
    <xml action="copy" source="xml/hst/workspace/newslist.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:containers"/>
    <xml action="copy" source="xml/hst/sitemap/news.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
  </instructionSet>
  <instructionSet>
    <file action="copy" source="java/NewsDocument.txt" target="{{beansFolder}}/NewsDocument.java"/>
  </instructionSet>


  <instructionSet>
    <xml action="copy" source="xml/hst/pages/newslist.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="xml/hst/pages/newspage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
  </instructionSet>


  <instructionSet>

    <xml action="copy" source="xml/hst/catalog/newslist.xml" target="/hst:hst/hst:configurations/hst:default/hst:catalog/essentials-catalog"/>
    <file action="copy" binary="true" source="images/news-list.png" target="{{imagesRoot}}/essentials/catalog-component-icons/news-list.png"/>
  </instructionSet>


  <!--
    //############################################
    // MENU
    //############################################
  -->
  <instructionSet>
    <xml action="copy" source="xml/hst/menu/menu-item-news.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:sitemenus/main"/>

  </instructionSet>

  <!-- SAMPLES GROUP-->
  <instructionSet group="sampleData">
    <folder path="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}" template="xml/content/news.xml"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_medusa.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_harvest.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/documents/news/sample_gastropoda.xml" target="/content/documents/{{namespace}}/news/{{dateRepoYearMonth}}"/>
    <xml action="copy" source="xml/samples/content/gallery/samples.xml" target="/content/gallery/{{namespace}}"/>
  </instructionSet>
  <!--
    CONFIG DATA
  -->

  <instructionSet>
    <xml action="copy" source="xml/folderoptions/new-news-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-news-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
   </instructionSet>
  <instructionSet>
    <file action="copy" binary="true" source="icons/new-folder-16.png" target="{{cmsRoot}}/src/main/resources/org/hippoecm/frontend/plugins/standardworkflow/new-news-folder-16.png"/>

  </instructionSet>


</instructions>

=== CapeSepias/essentials/dashboard-plugins/simple-content/src/main/resources/META-INF/simpleContent_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
  <instructionSet>
    <cnd documentType="contentdocument" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated,hippostd:taggable"/>
    <xml action="copy" source="xml/namespaces/contentdocument.xml" target="/hippo:namespaces/{{namespace}}"/>
    <file action="copy" source="java/ContentDocument.txt" target="{{beansFolder}}/ContentDocument.java"/>
  </instructionSet>

  <!-- HST TEMPLATES -->
  <instructionSet group="jsp">
    <xml action="copy" source="hst/template-content-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <file action="copy" source="jsp/essentials-simplecontent.jsp" target="{{jspRoot}}/essentials/essentials-simplecontent.jsp"/>
  </instructionSet>
  <instructionSet group="freemarker">
    <xml action="copy" source="hst/template-content-ftl.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <file action="copy" source="freemarker/essentials-simplecontent.ftl" target="{{freemarkerRoot}}/essentials/essentials-simplecontent.ftl"/>
  </instructionSet>
</instructions>
