=== CapeSepias/essentials/plugin-api/api/src/main/resources/instructions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.onehippo.org/essentials/instructions" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="instructions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="instructionSet">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="file" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="action" use="required"/>
                      <xs:attribute type="xs:string" name="source" use="optional"/>
                      <xs:attribute type="xs:string" name="target" use="optional"/>
                      <xs:attribute type="xs:string" name="overwrite" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="xml" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="action" use="required"/>
                      <xs:attribute type="xs:string" name="source" use="optional"/>
                      <xs:attribute type="xs:string" name="target" use="optional"/>
                      <xs:attribute type="xs:string" name="overwrite" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CapeSepias/essentials/dashboard-plugins/essentials-skeleton-package/src/main/resources/META-INF/commons_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright 2014 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
  <!--
  //############################################
  // COMMONS PACKAGE ADDS SHARED FILES/CONFIGURATION
  //############################################
  -->

  <instructionSet group="jsp">
    <!-- include-->
    <file action="copy" source="instructions/jsp/imports.jsp" target="{{jspRoot}}/include/imports.jsp"/>
    <file action="copy" source="instructions/jsp/pagination.jsp" target="{{jspRoot}}/include/pagination.jsp"/>
    <!-- skeleton-->
    <file action="copy" source="instructions/jsp/base-layout.jsp" target="{{jspRoot}}/{{namespace}}/base-layout.jsp"/>
    <file action="copy" source="instructions/jsp/base-top-menu.jsp" target="{{jspRoot}}/{{namespace}}/base-top-menu.jsp"/>
    <file action="copy" source="instructions/jsp/label-component.jsp" target="{{jspRoot}}/hstdefault/label-component.jsp"/>
  </instructionSet>
  <instructionSet group="jsp">
    <xml action="copy" source="instructions/xml/hst/templates/base-layout-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/base-top-menu-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/label-component-jsp.xml" target="/hst:hst/hst:configurations/hst:default/hst:templates"/>
  </instructionSet>

  <instructionSet group="freemarker, repository">
    <!-- include -->
    <freemarker action="copy" source="instructions/freemarker/imports.ftl" target="{{freemarkerRoot}}/include/imports.ftl"/>
    <freemarker action="copy" source="instructions/freemarker/pagination.ftl" target="{{freemarkerRoot}}/include/pagination.ftl"/>
     <!-- skeleton -->
    <freemarker action="copy" source="instructions/freemarker/base-layout.ftl" target="{{freemarkerRoot}}/{{namespace}}/base-layout.ftl"/>
    <freemarker action="copy" source="instructions/freemarker/base-top-menu.ftl" target="{{freemarkerRoot}}/{{namespace}}/base-top-menu.ftl"/>
    <freemarker action="copy" source="instructions/freemarker/label-component.ftl" target="{{freemarkerRoot}}/hstdefault/label-component.ftl"/>
  </instructionSet>
  <instructionSet group="freemarker">
    <xml action="copy" source="instructions/xml/hst/templates/base-layout-freemarker.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/base-top-menu-freemarker.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="instructions/xml/hst/templates/label-component-freemarker.xml" target="/hst:hst/hst:configurations/hst:default/hst:templates"/>
  </instructionSet>

  <!--
    //############################################
    // COMMON HST
    //############################################

  -->
  <instructionSet>
    <xml action="copy" source="instructions/xml/hst/workspace/base.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:containers"/>
    <xml action="copy" source="instructions/xml/hst/workspace/homepage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:containers"/>
    <!-- common -->
    <xml action="copy" source="instructions/xml/hst/sitemap/root.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
    <xml action="copy" source="instructions/xml/hst/menu/main.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:workspace/hst:sitemenus"/>

    <xml action="copy" source="instructions/xml/hst/pages/base.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:abstractpages"/>
    <xml action="copy" source="instructions/xml/hst/pages/homepage.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <!-- default-->
    <xml action="copy" source="instructions/xml/hst/catalog/essentials-catalog.xml" target="/hst:hst/hst:configurations/hst:default/hst:catalog"/>
    <xml action="copy" source="instructions/xml/hst/catalog/label.xml" target="/hst:hst/hst:configurations/hst:default/hst:catalog/essentials-catalog"/>

  </instructionSet>

  <!--
  //############################################
  // CSS/JS
  //############################################
-->
  <instructionSet>
    <file binary="true" action="copy" source="instructions/images/essentials-edit-component.png" target="{{imagesRoot}}/essentials-edit-component.png"/>
    <file binary="true" action="copy" source="instructions/images/label.png" target="{{imagesRoot}}/essentials/catalog-component-icons/label.png"/>
    <file binary="true" action="copy" source="instructions/js/bootstrap.min.js" target="{{javascriptRoot}}/bootstrap.min.js"/>
    <file binary="true" action="copy" source="instructions/js/jquery-2.1.0.min.js" target="{{javascriptRoot}}/jquery-2.1.0.min.js"/>
    <file action="copy" binary="true" source="instructions/bootstrap/css/bootstrap.css" target="{{siteWebRoot}}/css/bootstrap.css"/>
    <file action="copy" binary="true" source="instructions/bootstrap/css/bootstrap.min.css" target="{{siteWebRoot}}/css/bootstrap.min.css"/>
    <file action="copy" binary="true" source="instructions/css/cms-request.css" target="{{siteWebRoot}}/css/cms-request.css"/>
    <file action="copy" binary="true" source="instructions/bootstrap/fonts/glyphicons-halflings-regular.eot" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.eot"/>
    <file action="copy" binary="true" source="instructions/bootstrap/fonts/glyphicons-halflings-regular.svg" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.svg"/>
    <file action="copy" binary="true" source="instructions/bootstrap/fonts/glyphicons-halflings-regular.ttf" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.ttf"/>
    <file action="copy" binary="true" source="instructions/bootstrap/fonts/glyphicons-halflings-regular.woff" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.woff"/>
  </instructionSet>

</instructions>

=== CapeSepias/essentials/dashboard-plugins/banner-plugin/src/main/resources/META-INF/banner_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2014 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
  <!--
    DOCUMENT TYPES REGISTRATION
  -->
  <instructionSet>
    <!-- cnd-->
    <cnd documentType="bannerdocument" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated,hippostd:taggable"/>

    <!-- templates-->
    <xml action="copy" source="xml/namespaces/bannerdocument.xml" target="/hippo:namespaces/{{namespace}}"/>

    <!-- beans-->
    <file action="copy" source="java/Banner.txt" target="{{beansFolder}}/Banner.java"/>
    <!-- queries -->
    <xml action="copy" source="xml/configuration/new-banner-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/configuration/new-banner-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>


  </instructionSet>
  <!--
    //############################################
    // CAROUSEL COMPONENT
    //############################################

  -->
  <instructionSet group="jsp">
    <file action="copy" source="jsp/essentials-carousel.jsp" target="{{jspRoot}}/essentials/essentials-carousel.jsp"/>
    <file action="copy" source="jsp/essentials-banner.jsp" target="{{jspRoot}}/essentials/essentials-banner.jsp"/>
    <xml action="copy" source="hst/carousel-template-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="hst/banner-template-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
  </instructionSet>
  <instructionSet group="freemarker">
    <file action="copy" source="ftl/essentials-carousel.ftl" target="{{freemarkerRoot}}/essentials/essentials-carousel.ftl"/>
    <file action="copy" source="ftl/essentials-banner.ftl" target="{{freemarkerRoot}}/essentials/essentials-banner.ftk"/>
    <xml action="copy" source="hst/carousel-template-ftl.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <xml action="copy" source="hst/banner-template-ftl.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
  </instructionSet>
  <instructionSet>
    <xml action="copy" source="hst/carousel-catalog.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:catalog"/>

    <xml action="copy" source="hst/banner-template.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
    <file binary="true" action="copy" source="webapp/js/jquery-1.11.0.min.js" target="{{javascriptRoot}}/jquery-1.11.0.min.js"/>
    <file binary="true" action="copy" source="webapp/js/bootstrap.min.js" target="{{javascriptRoot}}/bootstrap.min.js"/>
    <file action="copy" binary="true" source="bootstrap/fonts/glyphicons-halflings-regular.eot" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.eot"/>
    <file action="copy" binary="true" source="bootstrap/fonts/glyphicons-halflings-regular.svg" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.svg"/>
    <file action="copy" binary="true" source="bootstrap/fonts/glyphicons-halflings-regular.ttf" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.ttf"/>
    <file action="copy" binary="true" source="bootstrap/fonts/glyphicons-halflings-regular.woff" target="{{siteWebRoot}}/fonts/glyphicons-halflings-regular.woff"/>
  </instructionSet>


  <!--
    SAMPLE DATA
  -->
  <instructionSet group="sampleData">
    <folder template="xml/data/banner-folder-creator.xml" path="/content/documents/{{namespace}}/banners"/>
    <xml action="copy" source="xml/data/banner_entry_1.xml" target="/content/documents/{{namespace}}/banners"/>
    <xml action="copy" source="xml/data/banner_entry_2.xml" target="/content/documents/{{namespace}}/banners"/>
    <xml action="copy" source="xml/data/banner_images.xml" target="/content/gallery/{{namespace}}"/>
  </instructionSet>


</instructions>

=== CapeSepias/essentials/dashboard-plugins/blog-plugin/src/main/resources/META-INF/blog_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
  <!--
    DOCUMENT TYPES REGISTRATION
  -->
  <instructionSet>
    <!-- cnd-->
    <cnd documentType="blogpost" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated"/>
    <cnd documentType="author" superType="{{namespace}}:basedocument,hippostd:relaxed,hippotranslation:translated"/>
    <cnd documentType="account" superType="hippo:compound,hippostd:relaxed"/>
    <!-- templates-->
    <xml action="copy" source="xml/namespaces/blogpost.xml" target="/hippo:namespaces/{{namespace}}"/>
    <xml action="copy" source="xml/namespaces/author.xml" target="/hippo:namespaces/{{namespace}}"/>
    <xml action="copy" source="xml/namespaces/account.xml" target="/hippo:namespaces/{{namespace}}"/>
    <!-- beans-->
    <file action="copy" overwrite="false" source="java/Author.txt" target="{{beansFolder}}/Author.java"/>
    <file action="copy" overwrite="false" source="java/Blogpost.txt" target="{{beansFolder}}/Blogpost.java"/>
    <file action="copy" overwrite="false" source="java/Account.txt" target="{{beansFolder}}/Account.java"/>
  </instructionSet>
  <!--
    COMPONENTS
  -->

  <!--
    CREATE FOLDER QUERIES
  -->
  <instructionSet>
    <xml action="copy" source="xml/folderoptions/new-blog-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-blog-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>

    <xml action="copy" source="xml/folderoptions/new-blogauthor-folder.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
    <xml action="copy" source="xml/folderoptions/new-blogauthor-document.xml" target="/hippo:configuration/hippo:queries/hippo:templates"/>
  </instructionSet>
  <!--
    CREATE DATA FOLDERS
  -->
  <instructionSet>
    <folder path="/content/documents/administration" template="xml/folder/administration_folder.xml"/>
    <folder path="/content/documents/{{namespace}}/blog/authors" template="xml/folder/blog_author_folder.xml"/>
    <folder path="/content/documents/{{namespace}}/blog/{{dateRepoYearMonth}}" template="xml/folder/blog_folder.xml"/>
  </instructionSet>
  <!--
    DATA
  -->

  <instructionSet>
    <xml action="copy" overwrite="false" source="xml/data/account-types.xml" target="/content/documents/administration"/>
    <xml action="copy" overwrite="false" source="xml/data/blog-categories.xml" target="/content/documents/administration"/>

  </instructionSet>

  <!--
    SAMPLE DATA
  -->
    <instructionSet>
      <xml action="copy" overwrite="false" source="xml/samples/author_1.xml" target="/content/documents/{{namespace}}/blog/authors"/>
      <xml action="copy" overwrite="false" source="xml/samples/author_2.xml" target="/content/documents/{{namespace}}/blog/authors"/>
      <xml action="copy" source="xml/samples/blog_entry_1.xml" target="/content/documents/{{namespace}}/blog/{{dateRepoYearMonth}}"/>
      <xml action="copy" source="xml/samples/blog_entry_2.xml" target="/content/documents/{{namespace}}/blog/{{dateRepoYearMonth}}"/>
    </instructionSet>

  <!--
    JSP TEMPLATES
  -->
  <instructionSet group="jsp">
    <file action="copy" overwrite="true" source="jsp/essentials-blog-detail.jsp" target="{{jspRoot}}/essentials/blog/essentials-blog-detail.jsp"/>
    <file action="copy" overwrite="true" source="jsp/essentials-blog-list.jsp" target="{{jspRoot}}/essentials/blog/essentials-blog-list.jsp"/>
  </instructionSet>
  <!--
    FREEMARKER TEMPLATES
  -->
  <instructionSet group="freemarker">
    <file action="copy" overwrite="true" source="freemarker/essentials-blog-detail.ftl" target="{{jspRoot}}/essentials/blog/essentials-blog-detail.ftl"/>
    <file action="copy" overwrite="true" source="freemarker/essentials-blog-list.ftl" target="{{jspRoot}}/essentials/blog/essentials-blog-list.ftl"/>
  </instructionSet>
  <!--
    FACET
  -->
  <instructionSet>
    <execute class="org.onehippo.cms7.essentials.dashboard.blog.FacetInstruction"/>
  </instructionSet>

</instructions>

=== CapeSepias/essentials/dashboard-plugins/components-plugin/components-gui/src/main/resources/META-INF/instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">
    <instructionSet>
        <file action="copy" overwrite="true" source="/essentials-component-document.jsp" target="${jspRoot}/essentials/essentials-component-document.jsp"/>
        <file action="copy" overwrite="true" source="/essentials-component-events.jsp" target="${jspRoot}/essentials/essentials-component-events.jsp"/>
        <file action="copy" overwrite="true" source="/essentials-component-event-detail.jsp" target="${jspRoot}/essentials/essentials-component-event-detail.jsp"/>
        <file action="copy" overwrite="true" source="/essentials-component-list.jsp" target="${jspRoot}/essentials/essentials-component-list.jsp"/>
        <file action="copy" overwrite="true" source="/essentials-component-news.jsp" target="${jspRoot}/essentials/essentials-component-news.jsp"/>
        <file action="copy" overwrite="true" source="/essentials-component-news-detail.jsp" target="${jspRoot}/essentials/essentials-component-news-details.jsp"/>

    </instructionSet>

</instructions>

=== CapeSepias/essentials/dashboard-plugins/search-plugin/src/main/resources/META-INF/searchPlugin_instructions.xml
<?xml version="1.0" encoding="UTF-8"?>
<instructions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.onehippo.org/essentials/instructions /instructions.xsd" xmlns="http://www.onehippo.org/essentials/instructions">

  <instructionSet>
    <xml action="copy" source="powerpack/xml/hst/search-catalog.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:catalog"/>
    <xml action="copy" source="powerpack/xml/hst/search-menu-item.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemenus/main"/>
    <xml action="copy" source="powerpack/xml/hst/search-page.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:pages"/>
    <xml action="copy" source="powerpack/xml/hst/search-sitemap.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:sitemap"/>
  </instructionSet>
  <instructionSet group="jsp">
    <file action="copy" source="powerpack/jsp/essentials-search.jsp" target="{{jspRoot}}/essentials/essentials-search.jsp"/>
    <xml action="copy" source="powerpack/xml/hst/search-template-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
  </instructionSet>
  <instructionSet group="freemarker">
    <file action="copy" source="powerpack/freemarker/essentials-search.ftl" target="{{freemarkerRoot}}/essentials/essentials-search.ftl"/>
    <xml action="copy" source="powerpack/xml/hst/search-template-jsp.xml" target="/hst:hst/hst:configurations/{{namespace}}/hst:templates"/>
  </instructionSet>
</instructions>
